baseURL = "https://hanazonochateau.net/"
languageCode = "ja-jp"
title = "花園シャトー107号室"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"
canonifyurls = true
enableRobotsTXT = true

[markup]
defaultMarkdownHandler = "goldmark"

[params]
copyright = "Copyright © 2022 Totsugekitai"
dark = "on"
highlight = true
commentForm = "https://forms.gle/Cc3R3fFMCQ9m6Rsr9"
description = "毎日眠いです。"
hitokoto = "春眠暁どころか真昼間を覚えず"
# hitokoto = "寒いと布団が気持ちいい"
# hitokoto = "冷房つけてベッドダイブ"
images = ["site_ogp.png"]

[menu]
[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/posts"
weight = 10

[[menu.main]]
identifier = "575"
name = "575"
title = "575"
url = "/575"
weight = 15

[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about"
weight = 20

[[menu.main]]
identifier = "comments"
name = "comments"
title = "comments"
url = "/comments"
weight = 25

[permalinks]
posts = "/posts/:year/:month/:day/:slug"
575 = "/575"
about = "/about"
comments = "/comments"
