baseURL = "https://hanazonochateau.net/"
languageCode = "ja-jp"
title = "花園シャトー107号室"
# theme = "hanazono"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "public"
canonifyurls = true
enableRobotsTXT = true
hasCJKLanguage = true
summaryLength = 80

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[module]
[[module.mounts]]
source = "s3"
target = "static/data"

[params]
author = "Totsugekitai"
highlight = true
commentForm = "https://forms.gle/Cc3R3fFMCQ9m6Rsr9"
description = "毎日眠いです。"
# hitokoto = "春眠暁どころか真昼間を覚えず"
# hitokoto = "寒いと布団が気持ちいい"
# hitokoto = "冷房つけてベッドダイブ"
# hitokoto = "夏風邪は咳が長引きます"
hitokoto = "実は生牡蠣より蒸し牡蠣が好きです"
images = ["site_ogp.png"]
